name: Electron Desktop App Build

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  Build:
    runs-on: macos-latest
    # permissions:
    #   contents: write
    #   pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
