name: Electron Desktop App Build

on:
  push:
    branches: ["main"]

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
  
      - uses: webiny/action-conventional-commits@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowed-commit-types: "feat,fix,chore,docs,style,refactor,perf,test,BREAKING CHANGE"
          
  Build:
    runs-on: macos-latest
    needs: conventional-commits
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: Build Electron Desktop App
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm install -y
      #     npm install -g electron-builder -y
      #     electron-builder --mac

      # - name: upload app
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: Augmet_Desktop
      #     path: |
      #       ./dist/electron-demo-1.0.0.dmg
      #       # ./dist/electron-demo_1.0.0_amd64.snap
      #       # ./dist/electron-demo Setup 1.0.0.exe

      # - name: Download artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: Augmet_Desktop
      #     path: ./Augmet_Desktop

      # - name: List downloaded artifacts
      #   run: |
      #     ls ./Augmet_Desktop
      #     zip -r Augmet_Desktop.zip ./Augmet_Desktop/
      #     ls ./

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.tag_version.outputs.changelog }}
          tag: ${{ steps.tag_version.outputs.new_tag }}

      # - name: upload artifact in the release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_name: Augmet_Desktop.zip
      #     asset_path: ./Augmet_Desktop.zip
      #     asset_content_type: application/zip
          
