name: Release Please testing
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  pull-requests: write

# jobs:
#   slackNotification:
#     name: Slack Notification
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Slack Notification
#       uses: rtCamp/action-slack-notify@v2
#       env:
#         # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#         SLACK_CHANNEL: random
#         SLACK_USERNAME: dhyey

jobs:
  spell-check:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: check-spelling
      #   id: spelling
      #   uses: check-spelling/check-spelling@main
      #   with:
      #     extra_dictionaries:
      #       cspell:software-terms/dict/softwareTerms.txt
      #       cspell:npm/dict/npm.txt
      #       cspell:typescript/dict/typescript.txt
      #       cspell:node/dict/node.txt
      #       cspell:k8s/dict/k8s.txt

      # - uses: wow-actions/spell-checker@v1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     include: **/*.md

      - uses: rojopolis/spellcheck-github-actions@0.35.0
        name: Spellcheck
        with:
          config: ./spellcheck.yaml
