name: Release Please
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

# jobs:
#   spell-check:
#     name: spell check
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - uses: rojopolis/spellcheck-github-actions@0.35.0
#         name: Spellcheck
#         with:
#           config: ./spellcheck.yaml
#           output_file: spellcheck-output.txt
          
#       - uses: actions/upload-artifact@v3
#         if: '!cancelled()' # Do not upload artifact if job was cancelled
#         with:
#           name: Spellcheck Output
#           path: spellcheck-output.txt


      # - uses: actions/upload-artifact@v3
      #   if: '!cancelled()' # Do not upload artifact if job was cancelled
      #   with:
      #     name: Spellcheck Output
      #     path: spellcheck-output.txt
